@spritepackutil.exe makestrip --suffix right_walk_1 --direction-order R --frame-order 0 %*
@spritepackutil.exe makestrip --suffix right_walk_2 --direction-order R --frame-order 1 %*
@spritepackutil.exe makestrip --suffix right_walk_3 --direction-order R --frame-order 2 %*
@spritepackutil.exe makestrip --suffix up_walk_1 --direction-order U --frame-order 0 %*
@spritepackutil.exe makestrip --suffix up_walk_2 --direction-order U --frame-order 1 %*
@spritepackutil.exe makestrip --suffix up_walk_3 --direction-order U --frame-order 2 %*
@spritepackutil.exe makestrip --suffix left_walk_1 --direction-order L --frame-order 0 %*
@spritepackutil.exe makestrip --suffix left_walk_2 --direction-order L --frame-order 1 %*
@spritepackutil.exe makestrip --suffix left_walk_3 --direction-order L --frame-order 2 %*
@spritepackutil.exe makestrip --suffix down_walk_1 --direction-order D --frame-order 0 %*
@spritepackutil.exe makestrip --suffix down_walk_2 --direction-order D --frame-order 1 %*
@spritepackutil.exe makestrip --suffix down_walk_3 --direction-order D --frame-order 2 %*
@spritepackutil.exe makestrip --suffix right_idle --direction-order R --frame-order 1 %*
@spritepackutil.exe makestrip --suffix up_idle --direction-order U --frame-order 1 %*
@spritepackutil.exe makestrip --suffix left_idle --direction-order L --frame-order 1 %*
@spritepackutil.exe makestrip --suffix down_idle --direction-order D --frame-order 1 %*